# Generated by Django 5.0.1 on 2024-02-13 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_store_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='added_date',
            new_name='date_added',
        ),
    ]
