# Generated by Django 5.0.1 on 2024-02-13 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store_app', '0002_rename_added_date_product_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='e_store_app.client'),
        ),
    ]
